### ISSUE TITLE
Support MQTT LWT (Last Will and Testament)

### ISSUE THREAD

**Issue by maorcc** [deiger/Alarm#8]
Can we support MQTT's LWT (Last Will and Testament)?
This will help Home Assistant identify early when the alarm is not working for any reason.

**Here are details of how LWT works:**  https://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament/

**Ref to Home Assistant community discussion:** https://community.home-assistant.io/t/expire-after-option-for-mqtt-alarm-control-panel/219260

**Comment by deiger** [comment]
Sure.

**Comment by maorcc** [comment]
The fix is working.  Thank you @deiger !
